export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';
export const LIST_REVIEW_FAILURE = 'LIST_REVIEW_FAILURE';
export const LIST_REVIEW_SUCCESS = 'LIST_REVIEW_SUCCESS'
